dist: xenial

sudo: false

language: cpp

os:
    - osx
    - linux

compiler:
    - clang
    - gcc

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - cmake
            - libgtest-dev
    brew:
        packages:
            - cmake
        env:
            - HOMEBREW_NO_AUTO_UPDATE=1

before_install:
    - |
        if [ $TRAVIS_OS_NAME = osx ]; then
            cd gtest
            sudo cmake CMakeLists.txt -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX -std=c++17 .
            sudo make
            sudo make install
            cd -
        elif [ $TRAVIS_OS_NAME = linux ]; then
            cd /usr/src/gtest
            sudo cmake CMakeLists.txt -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX -std=c++17 .
            sudo make
            sudo cp *.a /usr/lib
            cd -
        fi

install:
    - if [ $TRAVIS_OS_NAME = osx ]; then brew install lcov; fi

script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=coverage -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX -DUNIT_TESTING=true ..
    - make && make test

after_success:
    - |
        if [ $TRAVIS_OS_NAME = osx ] && [ $CXX = clang++ ]; then
            lcov --capture --directory . --output-file coverage.info
            lcov --remove coverage.info '/usr/*' --output-file coverage.info
            lcov --list coverage.info
            bash <(curl -s https://codecov.io/bash) -t "57886efc-8eca-416f-9e8b-1b0ee825efe5" -f coverage.info || echo "Codecov did not collect coverage reports"
        fi

notifications:
  email:
    - fjmw201@exeter.ac.uk
