dist: xenial
sudo: false
language: cpp

addons:
    apt:
        sources:
            - llvm-toolchain-trusty-7
        packages:
            - clang-7

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y libgtest-dev valgrind cmake
    - sudo wget https://github.com/google/googletest/archive/release-1.7.0.tar.gz
    - sudo tar xf release-1.7.0.tar.gz
    - cd googletest-release-1.7.0
    - sudo cmake -DBUILD_SHARED_LIBS=ON .
    - sudo make
    - sudo cp -a include/gtest /usr/include
    - sudo cp -a libgtest_main.so libgtest.so /usr/lib/
    - which valgrind
    - cd "${TRAVIS_BUILD_DIR}"

script:
    - export TRAVIS_COMPILER=clang++-7
    - export CXX=clang++-7
    - export CXX_FOR_BUILD=clang++-7
    - export CC=clang-7
    - export CC_FOR_BUILD=clang-7
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=debug -DCMAKE_C_COMPILER=clang-7 -DCMAKE_CXX_COMPILER=clang++-7 -DUNIT_TESTING=true ..
