language: c++

os:
    - osx

addons:
    homebrew:
        packages:
            - cmake
            - llvm

compiler:
    - clang

addons:
    - export PATH="/usr/local/opt/llvm/bin:$PATH"
    - export LDFLAGS="-L/usr/local/opt/llvm/lib"
    - export CPPFLAGS="-I/usr/local/opt/llvm/include"
    - export TRAVIS_COMPILER=clang++
    - export CXX=clang++
    - export CXX_FOR_BUILD=clang++
    - export CC=clang
    - export CC_FOR_BUILD=clang
    - which clang
    - clang --version
    - cd gtest
    - mkdir gtest/build
    - cd gtest/build
    - cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -std=c++20 -stdlib=libc++ ..
    - make
    - make install
    - cd -

script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=coverage -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DUNIT_TESTING=true ..
    - make && make test

after_success:
    - cpp-coveralls --root . -e "gtest/" -e "build/"
