dist: trusty
sudo: false
language: cpp

addons:
    apt:
        sources:
            - llvm-toolchain-trusty-7
        packages:
            - clang-7

script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=debug -DCMAKE_C_COMPILER=clang-7.0 -DCMAKE_CXX_COMPILER=clang++-7.0 -DUNIT_TESTING=true ..
