dist: xenial
sudo: false
language: cpp
os: linux
compiler: gcc

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - cmake
            - liggtest-dev
        env:
            - CC=gcc
            - CXX=g++

before_install:
    - sudo pip install codecov
    - cd /usr/src/gtest
    - sudo cmake CMakeLists.txt
    - sudo make
    - sudo cp *.a /usr/lib
    - cd -

script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=coverage -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DUNIT_TESTING=true ..
    - make && make test

after_success:
    - g++ --version
    - gcov --version
    - lcov --capture --directory . --output-file coverage.info
    - lcov --remove coverage.info '/usr/*' --output-file coverage.info
    - lcov --list coverage.info
    - bash <(curl -s https://codecov.io/bash) -t "57886efc-8eca-416f-9e8b-1b0ee825efe5" -f coverage.info || echo "Codecov did not collect coverage reports"

# notifications:
#   email:
#     - fjmw201@exeter.ac.uk
