dist: xenial
sudo: false
language: cpp
os: linux
compiler: clang

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - cmake
            - lcov
            - llvm
        env:
            - CC=clang
            - CXX=clang++

before_install:
    - cd gtest
    - sudo cmake CMakeLists.txt -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -std=c++17 .
    - sudo make
    - sudo make install
    - cd -

script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=coverage -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DUNIT_TESTING=true ..
    - make && make test

after_success:
    - lcov --capture --directory . --output-file coverage.info
    - lcov --remove coverage.info '/usr/*' --output-file coverage.info
    - lcov --list coverage.info
    - bash <(curl -s https://codecov.io/bash) -t "57886efc-8eca-416f-9e8b-1b0ee825efe5" -f coverage.info || echo "Codecov did not collect coverage reports"

# notifications:
#   email:
#     - fjmw201@exeter.ac.uk
