language: c++

os:
    - osx

addons:
    homebrew:
        packages:
            - cmake
            - llvm

compiler:
    - clang

addons:
    - export TRAVIS_COMPILER=clang++
    - export CXX=clang++
    - export CXX_FOR_BUILD=clang++
    - export CC=clang
    - export CC_FOR_BUILD=clang

script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=coverage -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DUNIT_TESTING=true ..
    - make && make test

after_success:
    - cpp-coveralls --root . -e "gtest/" -e "build/"
