dist: xenial
sudo: false
language: cpp

addons:
    apt:
        sources:
            - llvm-toolchain-trusty-7
        packages:
            - clang-7

before_install:
    - export TRAVIS_COMPILER=clang++-7
    - export CXX=clang++-7
    - export CXX_FOR_BUILD=clang++-7
    - export CC=clang-7
    - export CC_FOR_BUILD=clang-7
    - sudo apt-get -qq update
    - sudo apt-get install -y cmake
    - sudo apt-get install -y libgtest-dev
    - pip install --user gcovr
    - pip install --user cpp-coveralls
    - cd /usr/src/gtest
    - sudo cmake CMakeLists.txt
    - sudo make
    - sudo cp *.a /usr/lib
    - cd -

script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=coverage -DCMAKE_C_COMPILER=clang-7 -DCMAKE_CXX_COMPILER=clang++-7 -DUNIT_TESTING=true ..
    - make && make test

after_success:
    - cd -
    - cpp-coveralls -r . -e gtest/ -e build/ -b build/ --gcov-options '\-lp'
