//  == IMPORTS ==
//  -- Unit --
#include "arctk/si/dimension.inl"

//  -- GTest --
#include <gtest/gtest.h>



//  == PRAGMAS ==
//  -- Warnings --
#ifdef __clang__
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wglobal-constructors"
#endif



//  == ALIASES ==
//  -- Namespaces --
using namespace arc; // NOLINT



//  == NAMESPACE ==
namespace test
{



    //  == FIXTURES ==
    //  -- Dimension --
    class Dimension : public ::testing::Test
    {
        //  == FIELDS ==
      protected:
        //  -- Dimensions --
        const si::Scalar                         _immutable_scalar{-3.14159265358979323846};
        si::Scalar                               _mutable_scalar{-3.14159265358979323846};
        const si::Mass                           _immutable_mass{-3.14159265358979323846};
        si::Mass                                 _mutable_mass{-3.14159265358979323846};
        const si::Length                         _immutable_length{-3.14159265358979323846};
        si::Length                               _mutable_length{-3.14159265358979323846};
        const si::Time                           _immutable_time{-3.14159265358979323846};
        si::Time                                 _mutable_time{-3.14159265358979323846};
        const si::Temperature                    _immutable_temperature{-3.14159265358979323846};
        si::Temperature                          _mutable_temperature{-3.14159265358979323846};
        const si::Current                        _immutable_current{-3.14159265358979323846};
        si::Current                              _mutable_current{-3.14159265358979323846};
        const si::Intensity                      _immutable_intensity{-3.14159265358979323846};
        si::Intensity                            _mutable_intensity{-3.14159265358979323846};
        const si::Amount                         _immutable_amount{-3.14159265358979323846};
        si::Amount                               _mutable_amount{-3.14159265358979323846};
        const si::Angle                          _immutable_angle{-3.14159265358979323846};
        si::Angle                                _mutable_angle{-3.14159265358979323846};
        const si::SolidAngle                     _immutable_solid_angle{-3.14159265358979323846};
        si::SolidAngle                           _mutable_solid_angle{-3.14159265358979323846};
        const si::Area                           _immutable_area{-3.14159265358979323846};
        si::Area                                 _mutable_area{-3.14159265358979323846};
        const si::Volume                         _immutable_volume{-3.14159265358979323846};
        si::Volume                               _mutable_volume{-3.14159265358979323846};
        const si::Velocity                       _immutable_velocity{-3.14159265358979323846};
        si::Velocity                             _mutable_velocity{-3.14159265358979323846};
        const si::Acceleration                   _immutable_acceleration{-3.14159265358979323846};
        si::Acceleration                         _mutable_acceleration{-3.14159265358979323846};
        const si::Jerk                           _immutable_jerk{-3.14159265358979323846};
        si::Jerk                                 _mutable_jerk{-3.14159265358979323846};
        const si::Snap                           _immutable_snap{-3.14159265358979323846};
        si::Snap                                 _mutable_snap{-3.14159265358979323846};
        const si::Crackle                        _immutable_crackle{-3.14159265358979323846};
        si::Crackle                              _mutable_crackle{-3.14159265358979323846};
        const si::Pop                            _immutable_pop{-3.14159265358979323846};
        si::Pop                                  _mutable_pop{-3.14159265358979323846};
        const si::Wavenumber                     _immutable_wavenumber{-3.14159265358979323846};
        si::Wavenumber                           _mutable_wavenumber{-3.14159265358979323846};
        const si::Density                        _immutable_density{-3.14159265358979323846};
        si::Density                              _mutable_density{-3.14159265358979323846};
        const si::SurfaceDensity                 _immutable_surface_density{-3.14159265358979323846};
        si::SurfaceDensity                       _mutable_surface_density{-3.14159265358979323846};
        const si::SpecificVolume                 _immutable_specific_volume{-3.14159265358979323846};
        si::SpecificVolume                       _mutable_specific_volume{-3.14159265358979323846};
        const si::CurrentDensity                 _immutable_current_density{-3.14159265358979323846};
        si::CurrentDensity                       _mutable_current_density{-3.14159265358979323846};
        const si::MagneticFieldStrength          _immutable_magnetic_field_strength{-3.14159265358979323846};
        si::MagneticFieldStrength                _mutable_magnetic_field_strength{-3.14159265358979323846};
        const si::Concentration                  _immutable_concentration{-3.14159265358979323846};
        si::Concentration                        _mutable_concentration{-3.14159265358979323846};
        const si::Luminance                      _immutable_luminance{-3.14159265358979323846};
        si::Luminance                            _mutable_luminance{-3.14159265358979323846};
        const si::Illuminance                    _immutable_illuminance{-3.14159265358979323846};
        si::Illuminance                          _mutable_illuminance{-3.14159265358979323846};
        const si::Frequency                      _immutable_frequency{-3.14159265358979323846};
        si::Frequency                            _mutable_frequency{-3.14159265358979323846};
        const si::Force                          _immutable_force{-3.14159265358979323846};
        si::Force                                _mutable_force{-3.14159265358979323846};
        const si::Pressure                       _immutable_pressure{-3.14159265358979323846};
        si::Pressure                             _mutable_pressure{-3.14159265358979323846};
        const si::Stress                         _immutable_stress{-3.14159265358979323846};
        si::Stress                               _mutable_stress{-3.14159265358979323846};
        const si::EnergyDensity                  _immutable_energy_density{-3.14159265358979323846};
        si::EnergyDensity                        _mutable_energy_density{-3.14159265358979323846};
        const si::Energy                         _immutable_energy{-3.14159265358979323846};
        si::Energy                               _mutable_energy{-3.14159265358979323846};
        const si::Work                           _immutable_work{-3.14159265358979323846};
        si::Work                                 _mutable_work{-3.14159265358979323846};
        const si::Heat                           _immutable_heat{-3.14159265358979323846};
        si::Heat                                 _mutable_heat{-3.14159265358979323846};
        const si::Power                          _immutable_power{-3.14159265358979323846};
        si::Power                                _mutable_power{-3.14159265358979323846};
        const si::RadiantFlux                    _immutable_radiant_flux{-3.14159265358979323846};
        si::RadiantFlux                          _mutable_radiant_flux{-3.14159265358979323846};
        const si::Charge                         _immutable_charge{-3.14159265358979323846};
        si::Charge                               _mutable_charge{-3.14159265358979323846};
        const si::Potential                      _immutable_potential{-3.14159265358979323846};
        si::Potential                            _mutable_potential{-3.14159265358979323846};
        const si::Capacitance                    _immutable_capacitance{-3.14159265358979323846};
        si::Capacitance                          _mutable_capacitance{-3.14159265358979323846};
        const si::Resistance                     _immutable_resistance{-3.14159265358979323846};
        si::Resistance                           _mutable_resistance{-3.14159265358979323846};
        const si::Conductance                    _immutable_conductance{-3.14159265358979323846};
        si::Conductance                          _mutable_conductance{-3.14159265358979323846};
        const si::MagneticFlux                   _immutable_magnetic_flux{-3.14159265358979323846};
        si::MagneticFlux                         _mutable_magnetic_flux{-3.14159265358979323846};
        const si::MagneticFluxDensity            _immutable_magnetic_flux_density{-3.14159265358979323846};
        si::MagneticFluxDensity                  _mutable_magnetic_flux_density{-3.14159265358979323846};
        const si::Inductance                     _immutable_inductance{-3.14159265358979323846};
        si::Inductance                           _mutable_inductance{-3.14159265358979323846};
        const si::LuminousFlux                   _immutable_luminous_flux{-3.14159265358979323846};
        si::LuminousFlux                         _mutable_luminous_flux{-3.14159265358979323846};
        const si::Activity                       _immutable_activity{-3.14159265358979323846};
        si::Activity                             _mutable_activity{-3.14159265358979323846};
        const si::AbsorbedDose                   _immutable_absorbed_dose{-3.14159265358979323846};
        si::AbsorbedDose                         _mutable_absorbed_dose{-3.14159265358979323846};
        const si::Kerma                          _immutable_kerma{-3.14159265358979323846};
        si::Kerma                                _mutable_kerma{-3.14159265358979323846};
        const si::SpecificEnergy                 _immutable_specific_energy{-3.14159265358979323846};
        si::SpecificEnergy                       _mutable_specific_energy{-3.14159265358979323846};
        const si::DoseEquivalent                 _immutable_dose_equivalent{-3.14159265358979323846};
        si::DoseEquivalent                       _mutable_dose_equivalent{-3.14159265358979323846};
        const si::CatalyticActivity              _immutable_catalytic_activity{-3.14159265358979323846};
        si::CatalyticActivity                    _mutable_catalytic_activity{-3.14159265358979323846};
        const si::DynamicViscosity               _immutable_dynamic_viscosity{-3.14159265358979323846};
        si::DynamicViscosity                     _mutable_dynamic_viscosity{-3.14159265358979323846};
        const si::KinematicViscosity             _immutable_kinematic_viscosity{-3.14159265358979323846};
        si::KinematicViscosity                   _mutable_kinematic_viscosity{-3.14159265358979323846};
        const si::Moment                         _immutable_moment{-3.14159265358979323846};
        si::Moment                               _mutable_moment{-3.14159265358979323846};
        const si::SurfaceTension                 _immutable_surface_tension{-3.14159265358979323846};
        si::SurfaceTension                       _mutable_surface_tension{-3.14159265358979323846};
        const si::AngularVelocity                _immutable_angular_velocity{-3.14159265358979323846};
        si::AngularVelocity                      _mutable_angular_velocity{-3.14159265358979323846};
        const si::AngularAcceleration            _immutable_angular_acceleration{-3.14159265358979323846};
        si::AngularAcceleration                  _mutable_angular_acceleration{-3.14159265358979323846};
        const si::AngularJerk                    _immutable_angular_jerk{-3.14159265358979323846};
        si::AngularJerk                          _mutable_angular_jerk{-3.14159265358979323846};
        const si::AngularSnap                    _immutable_angular_snap{-3.14159265358979323846};
        si::AngularSnap                          _mutable_angular_snap{-3.14159265358979323846};
        const si::AngularCrackle                 _immutable_angular_crackle{-3.14159265358979323846};
        si::AngularCrackle                       _mutable_angular_crackle{-3.14159265358979323846};
        const si::AngularPop                     _immutable_angular_pop{-3.14159265358979323846};
        si::AngularPop                           _mutable_angular_pop{-3.14159265358979323846};
        const si::HeatFluxDensity                _immutable_heat_flux_density{-3.14159265358979323846};
        si::HeatFluxDensity                      _mutable_heat_flux_density{-3.14159265358979323846};
        const si::Irradiance                     _immutable_irradiance{-3.14159265358979323846};
        si::Irradiance                           _mutable_irradiance{-3.14159265358979323846};
        const si::HeatCapacity                   _immutable_heat_capacity{-3.14159265358979323846};
        si::HeatCapacity                         _mutable_heat_capacity{-3.14159265358979323846};
        const si::Entropy                        _immutable_entropy{-3.14159265358979323846};
        si::Entropy                              _mutable_entropy{-3.14159265358979323846};
        const si::SpecificHeatCapacity           _immutable_specific_heat_capacity{-3.14159265358979323846};
        si::SpecificHeatCapacity                 _mutable_specific_heat_capacity{-3.14159265358979323846};
        const si::SpecificEntropy                _immutable_specific_entropy{-3.14159265358979323846};
        si::SpecificEntropy                      _mutable_specific_entropy{-3.14159265358979323846};
        const si::ThermalConductivity            _immutable_thermal_conductivity{-3.14159265358979323846};
        si::ThermalConductivity                  _mutable_thermal_conductivity{-3.14159265358979323846};
        const si::ElectricFieldStrength          _immutable_electric_field_strength{-3.14159265358979323846};
        si::ElectricFieldStrength                _mutable_electric_field_strength{-3.14159265358979323846};
        const si::ElectricChargeDensity          _immutable_electric_charge_density{-3.14159265358979323846};
        si::ElectricChargeDensity                _mutable_electric_charge_density{-3.14159265358979323846};
        const si::SurfaceChargeDensity           _immutable_surface_charge_density{-3.14159265358979323846};
        si::SurfaceChargeDensity                 _mutable_surface_charge_density{-3.14159265358979323846};
        const si::ElectricFluxDensity            _immutable_electric_flux_density{-3.14159265358979323846};
        si::ElectricFluxDensity                  _mutable_electric_flux_density{-3.14159265358979323846};
        const si::ElectricDisplacement           _immutable_electric_displacement{-3.14159265358979323846};
        si::ElectricDisplacement                 _mutable_electric_displacement{-3.14159265358979323846};
        const si::Permittivity                   _immutable_permittivity{-3.14159265358979323846};
        si::Permittivity                         _mutable_permittivity{-3.14159265358979323846};
        const si::Permeability                   _immutable_permeability{-3.14159265358979323846};
        si::Permeability                         _mutable_permeability{-3.14159265358979323846};
        const si::MolarEnergy                    _immutable_molar_energy{-3.14159265358979323846};
        si::MolarEnergy                          _mutable_molar_energy{-3.14159265358979323846};
        const si::MolarEntropy                   _immutable_molar_entropy{-3.14159265358979323846};
        si::MolarEntropy                         _mutable_molar_entropy{-3.14159265358979323846};
        const si::MolarHeatCapacity              _immutable_molar_heat_capacity{-3.14159265358979323846};
        si::MolarHeatCapacity                    _mutable_molar_heat_capacity{-3.14159265358979323846};
        const si::Exposure                       _immutable_exposure{-3.14159265358979323846};
        si::Exposure                             _mutable_exposure{-3.14159265358979323846};
        const si::AbsorbedDoseRate               _immutable_absorbed_dose_rate{-3.14159265358979323846};
        si::AbsorbedDoseRate                     _mutable_absorbed_dose_rate{-3.14159265358979323846};
        const si::RadiantIntensity               _immutable_radiant_intensity{-3.14159265358979323846};
        si::RadiantIntensity                     _mutable_radiant_intensity{-3.14159265358979323846};
        const si::Radiance                       _immutable_radiance{-3.14159265358979323846};
        si::Radiance                             _mutable_radiance{-3.14159265358979323846};
        const si::CatalyticActivityConcentration _immutable_catalytic_activity_concentration{-3.14159265358979323846};
        si::CatalyticActivityConcentration       _mutable_catalytic_activity_concentration{-3.14159265358979323846};
        const si::Action                         _immutable_action{-3.14159265358979323846};
        si::Action                               _mutable_action{-3.14159265358979323846};
    };



    //  == CONSTANTS ==
    //  -- Bases --
    TEST_F(Dimension, MASS_EXPONENT) // NOLINT
    {
        ASSERT_EQ(si::Scalar::MASS_EXPONENT, 0);
        ASSERT_EQ(si::Mass::MASS_EXPONENT, 1);
        ASSERT_EQ(si::Length::MASS_EXPONENT, 0);
        ASSERT_EQ(si::Time::MASS_EXPONENT, 0);
        ASSERT_EQ(si::Temperature::MASS_EXPONENT, 0);
        ASSERT_EQ(si::Current::MASS_EXPONENT, 0);
        ASSERT_EQ(si::Intensity::MASS_EXPONENT, 0);
        ASSERT_EQ(si::Amount::MASS_EXPONENT, 0);
        ASSERT_EQ(si::Angle::MASS_EXPONENT, 0);
        ASSERT_EQ(si::SolidAngle::MASS_EXPONENT, 0);
        ASSERT_EQ(si::Area::MASS_EXPONENT, 0);
        ASSERT_EQ(si::Volume::MASS_EXPONENT, 0);
        ASSERT_EQ(si::Velocity::MASS_EXPONENT, 0);
        ASSERT_EQ(si::Acceleration::MASS_EXPONENT, 0);
        ASSERT_EQ(si::Jerk::MASS_EXPONENT, 0);
        ASSERT_EQ(si::Snap::MASS_EXPONENT, 0);
        ASSERT_EQ(si::Crackle::MASS_EXPONENT, 0);
        ASSERT_EQ(si::Pop::MASS_EXPONENT, 0);
        ASSERT_EQ(si::Wavenumber::MASS_EXPONENT, 0);
        ASSERT_EQ(si::Density::MASS_EXPONENT, 1);
        ASSERT_EQ(si::SurfaceDensity::MASS_EXPONENT, 1);
        ASSERT_EQ(si::SpecificVolume::MASS_EXPONENT, -1);
        ASSERT_EQ(si::CurrentDensity::MASS_EXPONENT, 0);
        ASSERT_EQ(si::MagneticFieldStrength::MASS_EXPONENT, 0);
        ASSERT_EQ(si::Concentration::MASS_EXPONENT, 0);
        ASSERT_EQ(si::Luminance::MASS_EXPONENT, 0);
        ASSERT_EQ(si::Illuminance::MASS_EXPONENT, 0);
        ASSERT_EQ(si::Frequency::MASS_EXPONENT, 0);
        ASSERT_EQ(si::Force::MASS_EXPONENT, 1);
        ASSERT_EQ(si::Pressure::MASS_EXPONENT, 1);
        ASSERT_EQ(si::Stress::MASS_EXPONENT, 1);
        ASSERT_EQ(si::EnergyDensity::MASS_EXPONENT, 1);
        ASSERT_EQ(si::Energy::MASS_EXPONENT, 1);
        ASSERT_EQ(si::Work::MASS_EXPONENT, 1);
        ASSERT_EQ(si::Heat::MASS_EXPONENT, 1);
        ASSERT_EQ(si::Power::MASS_EXPONENT, 1);
        ASSERT_EQ(si::RadiantFlux::MASS_EXPONENT, 1);
        ASSERT_EQ(si::Charge::MASS_EXPONENT, 0);
        ASSERT_EQ(si::Potential::MASS_EXPONENT, 1);
        ASSERT_EQ(si::Capacitance::MASS_EXPONENT, -1);
        ASSERT_EQ(si::Resistance::MASS_EXPONENT, 1);
        ASSERT_EQ(si::Conductance::MASS_EXPONENT, -1);
        ASSERT_EQ(si::MagneticFlux::MASS_EXPONENT, 1);
        ASSERT_EQ(si::MagneticFluxDensity::MASS_EXPONENT, 1);
        ASSERT_EQ(si::Inductance::MASS_EXPONENT, 1);
        ASSERT_EQ(si::LuminousFlux::MASS_EXPONENT, 0);
        ASSERT_EQ(si::Activity::MASS_EXPONENT, 0);
        ASSERT_EQ(si::AbsorbedDose::MASS_EXPONENT, 0);
        ASSERT_EQ(si::Kerma::MASS_EXPONENT, 0);
        ASSERT_EQ(si::SpecificEnergy::MASS_EXPONENT, 0);
        ASSERT_EQ(si::DoseEquivalent::MASS_EXPONENT, 0);
        ASSERT_EQ(si::CatalyticActivity::MASS_EXPONENT, 0);
        ASSERT_EQ(si::DynamicViscosity::MASS_EXPONENT, 1);
        ASSERT_EQ(si::KinematicViscosity::MASS_EXPONENT, 0);
        ASSERT_EQ(si::Moment::MASS_EXPONENT, 1);
        ASSERT_EQ(si::SurfaceTension::MASS_EXPONENT, 1);
        ASSERT_EQ(si::AngularVelocity::MASS_EXPONENT, 0);
        ASSERT_EQ(si::AngularAcceleration::MASS_EXPONENT, 0);
        ASSERT_EQ(si::AngularJerk::MASS_EXPONENT, 0);
        ASSERT_EQ(si::AngularSnap::MASS_EXPONENT, 0);
        ASSERT_EQ(si::AngularCrackle::MASS_EXPONENT, 0);
        ASSERT_EQ(si::AngularPop::MASS_EXPONENT, 0);
        ASSERT_EQ(si::HeatFluxDensity::MASS_EXPONENT, 1);
        ASSERT_EQ(si::Irradiance::MASS_EXPONENT, 1);
        ASSERT_EQ(si::HeatCapacity::MASS_EXPONENT, 1);
        ASSERT_EQ(si::Entropy::MASS_EXPONENT, 1);
        ASSERT_EQ(si::SpecificHeatCapacity::MASS_EXPONENT, 0);
        ASSERT_EQ(si::SpecificEntropy::MASS_EXPONENT, 0);
        ASSERT_EQ(si::ThermalConductivity::MASS_EXPONENT, 1);
        ASSERT_EQ(si::ElectricFieldStrength::MASS_EXPONENT, 1);
        ASSERT_EQ(si::ElectricChargeDensity::MASS_EXPONENT, 0);
        ASSERT_EQ(si::SurfaceChargeDensity::MASS_EXPONENT, 0);
        ASSERT_EQ(si::ElectricFluxDensity::MASS_EXPONENT, 0);
        ASSERT_EQ(si::ElectricDisplacement::MASS_EXPONENT, 0);
        ASSERT_EQ(si::Permittivity::MASS_EXPONENT, -1);
        ASSERT_EQ(si::Permeability::MASS_EXPONENT, 1);
        ASSERT_EQ(si::MolarEnergy::MASS_EXPONENT, 1);
        ASSERT_EQ(si::MolarEntropy::MASS_EXPONENT, 1);
        ASSERT_EQ(si::MolarHeatCapacity::MASS_EXPONENT, 1);
        ASSERT_EQ(si::Exposure::MASS_EXPONENT, -1);
        ASSERT_EQ(si::AbsorbedDoseRate::MASS_EXPONENT, 0);
        ASSERT_EQ(si::RadiantIntensity::MASS_EXPONENT, 1);
        ASSERT_EQ(si::Radiance::MASS_EXPONENT, 1);
        ASSERT_EQ(si::CatalyticActivityConcentration::MASS_EXPONENT, 0);
        ASSERT_EQ(si::Action::MASS_EXPONENT, 1);
    }

    TEST_F(Dimension, LENGTH_EXPONENT) // NOLINT
    {
        ASSERT_EQ(si::Scalar::LENGTH_EXPONENT, 0);
        ASSERT_EQ(si::Mass::LENGTH_EXPONENT, 0);
        ASSERT_EQ(si::Length::LENGTH_EXPONENT, 1);
        ASSERT_EQ(si::Time::LENGTH_EXPONENT, 0);
        ASSERT_EQ(si::Temperature::LENGTH_EXPONENT, 0);
        ASSERT_EQ(si::Current::LENGTH_EXPONENT, 0);
        ASSERT_EQ(si::Intensity::LENGTH_EXPONENT, 0);
        ASSERT_EQ(si::Amount::LENGTH_EXPONENT, 0);
        ASSERT_EQ(si::Angle::LENGTH_EXPONENT, 0);
        ASSERT_EQ(si::SolidAngle::LENGTH_EXPONENT, 0);
        ASSERT_EQ(si::Area::LENGTH_EXPONENT, 2);
        ASSERT_EQ(si::Volume::LENGTH_EXPONENT, 3);
        ASSERT_EQ(si::Velocity::LENGTH_EXPONENT, 1);
        ASSERT_EQ(si::Acceleration::LENGTH_EXPONENT, 1);
        ASSERT_EQ(si::Jerk::LENGTH_EXPONENT, 1);
        ASSERT_EQ(si::Snap::LENGTH_EXPONENT, 1);
        ASSERT_EQ(si::Crackle::LENGTH_EXPONENT, 1);
        ASSERT_EQ(si::Pop::LENGTH_EXPONENT, 1);
        ASSERT_EQ(si::Wavenumber::LENGTH_EXPONENT, -1);
        ASSERT_EQ(si::Density::LENGTH_EXPONENT, -3);
        ASSERT_EQ(si::SurfaceDensity::LENGTH_EXPONENT, -2);
        ASSERT_EQ(si::SpecificVolume::LENGTH_EXPONENT, 3);
        ASSERT_EQ(si::CurrentDensity::LENGTH_EXPONENT, -2);
        ASSERT_EQ(si::MagneticFieldStrength::LENGTH_EXPONENT, -1);
        ASSERT_EQ(si::Concentration::LENGTH_EXPONENT, -3);
        ASSERT_EQ(si::Luminance::LENGTH_EXPONENT, -2);
        ASSERT_EQ(si::Illuminance::LENGTH_EXPONENT, -2);
        ASSERT_EQ(si::Frequency::LENGTH_EXPONENT, 0);
        ASSERT_EQ(si::Force::LENGTH_EXPONENT, 1);
        ASSERT_EQ(si::Pressure::LENGTH_EXPONENT, -1);
        ASSERT_EQ(si::Stress::LENGTH_EXPONENT, -1);
        ASSERT_EQ(si::EnergyDensity::LENGTH_EXPONENT, -1);
        ASSERT_EQ(si::Energy::LENGTH_EXPONENT, 2);
        ASSERT_EQ(si::Work::LENGTH_EXPONENT, 2);
        ASSERT_EQ(si::Heat::LENGTH_EXPONENT, 2);
        ASSERT_EQ(si::Power::LENGTH_EXPONENT, 2);
        ASSERT_EQ(si::RadiantFlux::LENGTH_EXPONENT, 2);
        ASSERT_EQ(si::Charge::LENGTH_EXPONENT, 0);
        ASSERT_EQ(si::Potential::LENGTH_EXPONENT, 2);
        ASSERT_EQ(si::Capacitance::LENGTH_EXPONENT, -2);
        ASSERT_EQ(si::Resistance::LENGTH_EXPONENT, 2);
        ASSERT_EQ(si::Conductance::LENGTH_EXPONENT, -2);
        ASSERT_EQ(si::MagneticFlux::LENGTH_EXPONENT, 2);
        ASSERT_EQ(si::MagneticFluxDensity::LENGTH_EXPONENT, 0);
        ASSERT_EQ(si::Inductance::LENGTH_EXPONENT, 2);
        ASSERT_EQ(si::LuminousFlux::LENGTH_EXPONENT, 0);
        ASSERT_EQ(si::Activity::LENGTH_EXPONENT, 0);
        ASSERT_EQ(si::AbsorbedDose::LENGTH_EXPONENT, 2);
        ASSERT_EQ(si::Kerma::LENGTH_EXPONENT, 2);
        ASSERT_EQ(si::SpecificEnergy::LENGTH_EXPONENT, 2);
        ASSERT_EQ(si::DoseEquivalent::LENGTH_EXPONENT, 2);
        ASSERT_EQ(si::CatalyticActivity::LENGTH_EXPONENT, 0);
        ASSERT_EQ(si::DynamicViscosity::LENGTH_EXPONENT, -1);
        ASSERT_EQ(si::KinematicViscosity::LENGTH_EXPONENT, 2);
        ASSERT_EQ(si::Moment::LENGTH_EXPONENT, 2);
        ASSERT_EQ(si::SurfaceTension::LENGTH_EXPONENT, 0);
        ASSERT_EQ(si::AngularVelocity::LENGTH_EXPONENT, 0);
        ASSERT_EQ(si::AngularAcceleration::LENGTH_EXPONENT, 0);
        ASSERT_EQ(si::AngularJerk::LENGTH_EXPONENT, 0);
        ASSERT_EQ(si::AngularSnap::LENGTH_EXPONENT, 0);
        ASSERT_EQ(si::AngularCrackle::LENGTH_EXPONENT, 0);
        ASSERT_EQ(si::AngularPop::LENGTH_EXPONENT, 0);
        ASSERT_EQ(si::HeatFluxDensity::LENGTH_EXPONENT, 0);
        ASSERT_EQ(si::Irradiance::LENGTH_EXPONENT, 0);
        ASSERT_EQ(si::HeatCapacity::LENGTH_EXPONENT, 2);
        ASSERT_EQ(si::Entropy::LENGTH_EXPONENT, 2);
        ASSERT_EQ(si::SpecificHeatCapacity::LENGTH_EXPONENT, 2);
        ASSERT_EQ(si::SpecificEntropy::LENGTH_EXPONENT, 2);
        ASSERT_EQ(si::ThermalConductivity::LENGTH_EXPONENT, 1);
        ASSERT_EQ(si::ElectricFieldStrength::LENGTH_EXPONENT, 1);
        ASSERT_EQ(si::ElectricChargeDensity::LENGTH_EXPONENT, -3);
        ASSERT_EQ(si::SurfaceChargeDensity::LENGTH_EXPONENT, -2);
        ASSERT_EQ(si::ElectricFluxDensity::LENGTH_EXPONENT, -2);
        ASSERT_EQ(si::ElectricDisplacement::LENGTH_EXPONENT, -2);
        ASSERT_EQ(si::Permittivity::LENGTH_EXPONENT, -3);
        ASSERT_EQ(si::Permeability::LENGTH_EXPONENT, 1);
        ASSERT_EQ(si::MolarEnergy::LENGTH_EXPONENT, 2);
        ASSERT_EQ(si::MolarEntropy::LENGTH_EXPONENT, 2);
        ASSERT_EQ(si::MolarHeatCapacity::LENGTH_EXPONENT, 2);
        ASSERT_EQ(si::Exposure::LENGTH_EXPONENT, 0);
        ASSERT_EQ(si::AbsorbedDoseRate::LENGTH_EXPONENT, 2);
        ASSERT_EQ(si::RadiantIntensity::LENGTH_EXPONENT, 2);
        ASSERT_EQ(si::Radiance::LENGTH_EXPONENT, 0);
        ASSERT_EQ(si::CatalyticActivityConcentration::LENGTH_EXPONENT, -3);
        ASSERT_EQ(si::Action::LENGTH_EXPONENT, 2);
    }

    TEST_F(Dimension, TIME_EXPONENT) // NOLINT
    {
        ASSERT_EQ(si::Scalar::TIME_EXPONENT, 0);
        ASSERT_EQ(si::Mass::TIME_EXPONENT, 0);
        ASSERT_EQ(si::Length::TIME_EXPONENT, 0);
        ASSERT_EQ(si::Time::TIME_EXPONENT, 1);
        ASSERT_EQ(si::Temperature::TIME_EXPONENT, 0);
        ASSERT_EQ(si::Current::TIME_EXPONENT, 0);
        ASSERT_EQ(si::Intensity::TIME_EXPONENT, 0);
        ASSERT_EQ(si::Amount::TIME_EXPONENT, 0);
        ASSERT_EQ(si::Angle::TIME_EXPONENT, 0);
        ASSERT_EQ(si::SolidAngle::TIME_EXPONENT, 0);
        ASSERT_EQ(si::Area::TIME_EXPONENT, 0);
        ASSERT_EQ(si::Volume::TIME_EXPONENT, 0);
        ASSERT_EQ(si::Velocity::TIME_EXPONENT, -1);
        ASSERT_EQ(si::Acceleration::TIME_EXPONENT, -2);
        ASSERT_EQ(si::Jerk::TIME_EXPONENT, -3);
        ASSERT_EQ(si::Snap::TIME_EXPONENT, -4);
        ASSERT_EQ(si::Crackle::TIME_EXPONENT, -5);
        ASSERT_EQ(si::Pop::TIME_EXPONENT, -6);
        ASSERT_EQ(si::Wavenumber::TIME_EXPONENT, 0);
        ASSERT_EQ(si::Density::TIME_EXPONENT, 0);
        ASSERT_EQ(si::SurfaceDensity::TIME_EXPONENT, 0);
        ASSERT_EQ(si::SpecificVolume::TIME_EXPONENT, 0);
        ASSERT_EQ(si::CurrentDensity::TIME_EXPONENT, 0);
        ASSERT_EQ(si::MagneticFieldStrength::TIME_EXPONENT, 0);
        ASSERT_EQ(si::Concentration::TIME_EXPONENT, 0);
        ASSERT_EQ(si::Luminance::TIME_EXPONENT, 0);
        ASSERT_EQ(si::Illuminance::TIME_EXPONENT, 0);
        ASSERT_EQ(si::Frequency::TIME_EXPONENT, -1);
        ASSERT_EQ(si::Force::TIME_EXPONENT, -2);
        ASSERT_EQ(si::Pressure::TIME_EXPONENT, -2);
        ASSERT_EQ(si::Stress::TIME_EXPONENT, -2);
        ASSERT_EQ(si::EnergyDensity::TIME_EXPONENT, -2);
        ASSERT_EQ(si::Energy::TIME_EXPONENT, -2);
        ASSERT_EQ(si::Work::TIME_EXPONENT, -2);
        ASSERT_EQ(si::Heat::TIME_EXPONENT, -2);
        ASSERT_EQ(si::Power::TIME_EXPONENT, -3);
        ASSERT_EQ(si::RadiantFlux::TIME_EXPONENT, -3);
        ASSERT_EQ(si::Charge::TIME_EXPONENT, 1);
        ASSERT_EQ(si::Potential::TIME_EXPONENT, -3);
        ASSERT_EQ(si::Capacitance::TIME_EXPONENT, 4);
        ASSERT_EQ(si::Resistance::TIME_EXPONENT, -3);
        ASSERT_EQ(si::Conductance::TIME_EXPONENT, 3);
        ASSERT_EQ(si::MagneticFlux::TIME_EXPONENT, -2);
        ASSERT_EQ(si::MagneticFluxDensity::TIME_EXPONENT, -2);
        ASSERT_EQ(si::Inductance::TIME_EXPONENT, -2);
        ASSERT_EQ(si::LuminousFlux::TIME_EXPONENT, 0);
        ASSERT_EQ(si::Activity::TIME_EXPONENT, -1);
        ASSERT_EQ(si::AbsorbedDose::TIME_EXPONENT, -2);
        ASSERT_EQ(si::Kerma::TIME_EXPONENT, -2);
        ASSERT_EQ(si::SpecificEnergy::TIME_EXPONENT, -2);
        ASSERT_EQ(si::DoseEquivalent::TIME_EXPONENT, -2);
        ASSERT_EQ(si::CatalyticActivity::TIME_EXPONENT, -1);
        ASSERT_EQ(si::DynamicViscosity::TIME_EXPONENT, -1);
        ASSERT_EQ(si::KinematicViscosity::TIME_EXPONENT, -1);
        ASSERT_EQ(si::Moment::TIME_EXPONENT, -2);
        ASSERT_EQ(si::SurfaceTension::TIME_EXPONENT, -2);
        ASSERT_EQ(si::AngularVelocity::TIME_EXPONENT, -1);
        ASSERT_EQ(si::AngularAcceleration::TIME_EXPONENT, -2);
        ASSERT_EQ(si::AngularJerk::TIME_EXPONENT, -3);
        ASSERT_EQ(si::AngularSnap::TIME_EXPONENT, -4);
        ASSERT_EQ(si::AngularCrackle::TIME_EXPONENT, -5);
        ASSERT_EQ(si::AngularPop::TIME_EXPONENT, -6);
        ASSERT_EQ(si::HeatFluxDensity::TIME_EXPONENT, -3);
        ASSERT_EQ(si::Irradiance::TIME_EXPONENT, -3);
        ASSERT_EQ(si::HeatCapacity::TIME_EXPONENT, -2);
        ASSERT_EQ(si::Entropy::TIME_EXPONENT, -2);
        ASSERT_EQ(si::SpecificHeatCapacity::TIME_EXPONENT, -2);
        ASSERT_EQ(si::SpecificEntropy::TIME_EXPONENT, -2);
        ASSERT_EQ(si::ThermalConductivity::TIME_EXPONENT, -3);
        ASSERT_EQ(si::ElectricFieldStrength::TIME_EXPONENT, -3);
        ASSERT_EQ(si::ElectricChargeDensity::TIME_EXPONENT, 1);
        ASSERT_EQ(si::SurfaceChargeDensity::TIME_EXPONENT, 1);
        ASSERT_EQ(si::ElectricFluxDensity::TIME_EXPONENT, 1);
        ASSERT_EQ(si::ElectricDisplacement::TIME_EXPONENT, 1);
        ASSERT_EQ(si::Permittivity::TIME_EXPONENT, 4);
        ASSERT_EQ(si::Permeability::TIME_EXPONENT, -2);
        ASSERT_EQ(si::MolarEnergy::TIME_EXPONENT, -2);
        ASSERT_EQ(si::MolarEntropy::TIME_EXPONENT, -2);
        ASSERT_EQ(si::MolarHeatCapacity::TIME_EXPONENT, -2);
        ASSERT_EQ(si::Exposure::TIME_EXPONENT, 1);
        ASSERT_EQ(si::AbsorbedDoseRate::TIME_EXPONENT, -3);
        ASSERT_EQ(si::RadiantIntensity::TIME_EXPONENT, -3);
        ASSERT_EQ(si::Radiance::TIME_EXPONENT, -3);
        ASSERT_EQ(si::CatalyticActivityConcentration::TIME_EXPONENT, -1);
        ASSERT_EQ(si::Action::TIME_EXPONENT, -1);
    }

    TEST_F(Dimension, TEMPERATURE_EXPONENT) // NOLINT
    {
        ASSERT_EQ(si::Scalar::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::Mass::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::Length::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::Time::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::Temperature::TEMPERATURE_EXPONENT, 1);
        ASSERT_EQ(si::Current::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::Intensity::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::Amount::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::Angle::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::SolidAngle::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::Area::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::Volume::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::Velocity::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::Acceleration::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::Jerk::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::Snap::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::Crackle::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::Pop::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::Wavenumber::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::Density::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::SurfaceDensity::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::SpecificVolume::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::CurrentDensity::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::MagneticFieldStrength::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::Concentration::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::Luminance::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::Illuminance::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::Frequency::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::Force::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::Pressure::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::Stress::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::EnergyDensity::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::Energy::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::Work::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::Heat::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::Power::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::RadiantFlux::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::Charge::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::Potential::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::Capacitance::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::Resistance::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::Conductance::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::MagneticFlux::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::MagneticFluxDensity::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::Inductance::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::LuminousFlux::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::Activity::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::AbsorbedDose::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::Kerma::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::SpecificEnergy::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::DoseEquivalent::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::CatalyticActivity::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::DynamicViscosity::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::KinematicViscosity::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::Moment::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::SurfaceTension::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::AngularVelocity::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::AngularAcceleration::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::AngularJerk::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::AngularSnap::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::AngularCrackle::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::AngularPop::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::HeatFluxDensity::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::Irradiance::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::HeatCapacity::TEMPERATURE_EXPONENT, -1);
        ASSERT_EQ(si::Entropy::TEMPERATURE_EXPONENT, -1);
        ASSERT_EQ(si::SpecificHeatCapacity::TEMPERATURE_EXPONENT, -1);
        ASSERT_EQ(si::SpecificEntropy::TEMPERATURE_EXPONENT, -1);
        ASSERT_EQ(si::ThermalConductivity::TEMPERATURE_EXPONENT, -1);
        ASSERT_EQ(si::ElectricFieldStrength::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::ElectricChargeDensity::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::SurfaceChargeDensity::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::ElectricFluxDensity::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::ElectricDisplacement::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::Permittivity::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::Permeability::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::MolarEnergy::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::MolarEntropy::TEMPERATURE_EXPONENT, -1);
        ASSERT_EQ(si::MolarHeatCapacity::TEMPERATURE_EXPONENT, -1);
        ASSERT_EQ(si::Exposure::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::AbsorbedDoseRate::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::RadiantIntensity::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::Radiance::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::CatalyticActivityConcentration::TEMPERATURE_EXPONENT, 0);
        ASSERT_EQ(si::Action::TEMPERATURE_EXPONENT, 0);
    }

    TEST_F(Dimension, CURRENT_EXPONENT) // NOLINT
    {
        ASSERT_EQ(si::Scalar::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::Mass::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::Length::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::Time::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::Temperature::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::Current::CURRENT_EXPONENT, 1);
        ASSERT_EQ(si::Intensity::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::Amount::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::Angle::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::SolidAngle::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::Area::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::Volume::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::Velocity::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::Acceleration::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::Jerk::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::Snap::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::Crackle::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::Pop::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::Wavenumber::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::Density::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::SurfaceDensity::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::SpecificVolume::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::CurrentDensity::CURRENT_EXPONENT, 1);
        ASSERT_EQ(si::MagneticFieldStrength::CURRENT_EXPONENT, 1);
        ASSERT_EQ(si::Concentration::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::Luminance::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::Illuminance::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::Frequency::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::Force::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::Pressure::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::Stress::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::EnergyDensity::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::Energy::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::Work::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::Heat::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::Power::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::RadiantFlux::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::Charge::CURRENT_EXPONENT, 1);
        ASSERT_EQ(si::Potential::CURRENT_EXPONENT, -1);
        ASSERT_EQ(si::Capacitance::CURRENT_EXPONENT, -1);
        ASSERT_EQ(si::Resistance::CURRENT_EXPONENT, -2);
        ASSERT_EQ(si::Conductance::CURRENT_EXPONENT, 2);
        ASSERT_EQ(si::MagneticFlux::CURRENT_EXPONENT, -1);
        ASSERT_EQ(si::MagneticFluxDensity::CURRENT_EXPONENT, -1);
        ASSERT_EQ(si::Inductance::CURRENT_EXPONENT, -2);
        ASSERT_EQ(si::LuminousFlux::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::Activity::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::AbsorbedDose::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::Kerma::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::SpecificEnergy::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::DoseEquivalent::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::CatalyticActivity::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::DynamicViscosity::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::KinematicViscosity::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::Moment::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::SurfaceTension::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::AngularVelocity::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::AngularAcceleration::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::AngularJerk::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::AngularSnap::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::AngularCrackle::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::AngularPop::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::HeatFluxDensity::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::Irradiance::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::HeatCapacity::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::Entropy::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::SpecificHeatCapacity::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::SpecificEntropy::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::ThermalConductivity::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::ElectricFieldStrength::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::ElectricChargeDensity::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::SurfaceChargeDensity::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::ElectricFluxDensity::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::ElectricDisplacement::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::Permittivity::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::Permeability::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::MolarEnergy::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::MolarEntropy::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::MolarHeatCapacity::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::Exposure::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::AbsorbedDoseRate::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::RadiantIntensity::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::Radiance::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::CatalyticActivityConcentration::CURRENT_EXPONENT, 0);
        ASSERT_EQ(si::Action::CURRENT_EXPONENT, 0);
    }

    TEST_F(Dimension, INTENSITY_EXPONENT) // NOLINT
    {
        ASSERT_EQ(si::Scalar::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::Mass::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::Length::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::Time::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::Temperature::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::Current::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::Intensity::INTENSITY_EXPONENT, 1);
        ASSERT_EQ(si::Amount::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::Angle::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::SolidAngle::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::Area::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::Volume::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::Velocity::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::Acceleration::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::Jerk::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::Snap::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::Crackle::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::Pop::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::Wavenumber::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::Density::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::SurfaceDensity::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::SpecificVolume::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::CurrentDensity::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::MagneticFieldStrength::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::Concentration::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::Luminance::INTENSITY_EXPONENT, 1);
        ASSERT_EQ(si::Illuminance::INTENSITY_EXPONENT, 1);
        ASSERT_EQ(si::Frequency::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::Force::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::Pressure::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::Stress::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::EnergyDensity::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::Energy::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::Work::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::Heat::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::Power::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::RadiantFlux::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::Charge::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::Potential::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::Capacitance::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::Resistance::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::Conductance::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::MagneticFlux::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::MagneticFluxDensity::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::Inductance::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::LuminousFlux::INTENSITY_EXPONENT, 1);
        ASSERT_EQ(si::Activity::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::AbsorbedDose::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::Kerma::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::SpecificEnergy::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::DoseEquivalent::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::CatalyticActivity::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::DynamicViscosity::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::KinematicViscosity::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::Moment::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::SurfaceTension::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::AngularVelocity::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::AngularAcceleration::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::AngularJerk::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::AngularSnap::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::AngularCrackle::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::AngularPop::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::HeatFluxDensity::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::Irradiance::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::HeatCapacity::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::Entropy::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::SpecificHeatCapacity::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::SpecificEntropy::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::ThermalConductivity::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::ElectricFieldStrength::INTENSITY_EXPONENT, -1);
        ASSERT_EQ(si::ElectricChargeDensity::INTENSITY_EXPONENT, 1);
        ASSERT_EQ(si::SurfaceChargeDensity::INTENSITY_EXPONENT, 1);
        ASSERT_EQ(si::ElectricFluxDensity::INTENSITY_EXPONENT, 1);
        ASSERT_EQ(si::ElectricDisplacement::INTENSITY_EXPONENT, 1);
        ASSERT_EQ(si::Permittivity::INTENSITY_EXPONENT, 2);
        ASSERT_EQ(si::Permeability::INTENSITY_EXPONENT, -2);
        ASSERT_EQ(si::MolarEnergy::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::MolarEntropy::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::MolarHeatCapacity::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::Exposure::INTENSITY_EXPONENT, 1);
        ASSERT_EQ(si::AbsorbedDoseRate::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::RadiantIntensity::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::Radiance::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::CatalyticActivityConcentration::INTENSITY_EXPONENT, 0);
        ASSERT_EQ(si::Action::INTENSITY_EXPONENT, 0);
    }

    TEST_F(Dimension, AMOUNT_EXPONENT) // NOLINT
    {
        ASSERT_EQ(si::Scalar::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::Mass::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::Length::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::Time::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::Temperature::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::Current::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::Intensity::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::Amount::AMOUNT_EXPONENT, 1);
        ASSERT_EQ(si::Angle::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::SolidAngle::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::Area::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::Volume::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::Velocity::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::Acceleration::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::Jerk::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::Snap::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::Crackle::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::Pop::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::Wavenumber::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::Density::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::SurfaceDensity::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::SpecificVolume::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::CurrentDensity::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::MagneticFieldStrength::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::Concentration::AMOUNT_EXPONENT, 1);
        ASSERT_EQ(si::Luminance::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::Illuminance::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::Frequency::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::Force::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::Pressure::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::Stress::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::EnergyDensity::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::Energy::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::Work::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::Heat::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::Power::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::RadiantFlux::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::Charge::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::Potential::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::Capacitance::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::Resistance::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::Conductance::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::MagneticFlux::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::MagneticFluxDensity::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::Inductance::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::LuminousFlux::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::Activity::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::AbsorbedDose::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::Kerma::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::SpecificEnergy::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::DoseEquivalent::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::CatalyticActivity::AMOUNT_EXPONENT, 1);
        ASSERT_EQ(si::DynamicViscosity::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::KinematicViscosity::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::Moment::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::SurfaceTension::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::AngularVelocity::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::AngularAcceleration::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::AngularJerk::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::AngularSnap::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::AngularCrackle::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::AngularPop::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::HeatFluxDensity::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::Irradiance::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::HeatCapacity::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::Entropy::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::SpecificHeatCapacity::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::SpecificEntropy::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::ThermalConductivity::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::ElectricFieldStrength::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::ElectricChargeDensity::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::SurfaceChargeDensity::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::ElectricFluxDensity::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::ElectricDisplacement::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::Permittivity::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::Permeability::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::MolarEnergy::AMOUNT_EXPONENT, -1);
        ASSERT_EQ(si::MolarEntropy::AMOUNT_EXPONENT, -1);
        ASSERT_EQ(si::MolarHeatCapacity::AMOUNT_EXPONENT, -1);
        ASSERT_EQ(si::Exposure::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::AbsorbedDoseRate::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::RadiantIntensity::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::Radiance::AMOUNT_EXPONENT, 0);
        ASSERT_EQ(si::CatalyticActivityConcentration::AMOUNT_EXPONENT, 1);
        ASSERT_EQ(si::Action::AMOUNT_EXPONENT, 0);
    }

    TEST_F(Dimension, ANGLE_EXPONENT) // NOLINT
    {
        ASSERT_EQ(si::Scalar::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::Mass::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::Length::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::Time::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::Temperature::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::Current::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::Intensity::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::Amount::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::Angle::ANGLE_EXPONENT, 1);
        ASSERT_EQ(si::SolidAngle::ANGLE_EXPONENT, 2);
        ASSERT_EQ(si::Area::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::Volume::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::Velocity::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::Acceleration::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::Jerk::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::Snap::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::Crackle::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::Pop::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::Wavenumber::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::Density::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::SurfaceDensity::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::SpecificVolume::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::CurrentDensity::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::MagneticFieldStrength::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::Concentration::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::Luminance::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::Illuminance::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::Frequency::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::Force::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::Pressure::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::Stress::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::EnergyDensity::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::Energy::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::Work::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::Heat::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::Power::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::RadiantFlux::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::Charge::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::Potential::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::Capacitance::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::Resistance::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::Conductance::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::MagneticFlux::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::MagneticFluxDensity::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::Inductance::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::LuminousFlux::ANGLE_EXPONENT, 2);
        ASSERT_EQ(si::Activity::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::AbsorbedDose::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::Kerma::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::SpecificEnergy::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::DoseEquivalent::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::CatalyticActivity::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::DynamicViscosity::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::KinematicViscosity::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::Moment::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::SurfaceTension::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::AngularVelocity::ANGLE_EXPONENT, 1);
        ASSERT_EQ(si::AngularAcceleration::ANGLE_EXPONENT, 1);
        ASSERT_EQ(si::AngularJerk::ANGLE_EXPONENT, 1);
        ASSERT_EQ(si::AngularSnap::ANGLE_EXPONENT, 1);
        ASSERT_EQ(si::AngularCrackle::ANGLE_EXPONENT, 1);
        ASSERT_EQ(si::AngularPop::ANGLE_EXPONENT, 1);
        ASSERT_EQ(si::HeatFluxDensity::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::Irradiance::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::HeatCapacity::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::Entropy::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::SpecificHeatCapacity::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::SpecificEntropy::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::ThermalConductivity::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::ElectricFieldStrength::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::ElectricChargeDensity::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::SurfaceChargeDensity::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::ElectricFluxDensity::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::ElectricDisplacement::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::Permittivity::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::Permeability::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::MolarEnergy::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::MolarEntropy::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::MolarHeatCapacity::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::Exposure::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::AbsorbedDoseRate::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::RadiantIntensity::ANGLE_EXPONENT, 2);
        ASSERT_EQ(si::Radiance::ANGLE_EXPONENT, 2);
        ASSERT_EQ(si::CatalyticActivityConcentration::ANGLE_EXPONENT, 0);
        ASSERT_EQ(si::Action::ANGLE_EXPONENT, 0);
    }

    TEST_F(Dimension, UNITS) // NOLINT
    {
        ASSERT_STREQ(si::Scalar::UNITS, "_");
        ASSERT_STREQ(si::Mass::UNITS, "kg");
        ASSERT_STREQ(si::Length::UNITS, "m");
        ASSERT_STREQ(si::Time::UNITS, "s");
        ASSERT_STREQ(si::Temperature::UNITS, "K");
        ASSERT_STREQ(si::Current::UNITS, "A");
        ASSERT_STREQ(si::Intensity::UNITS, "cd");
        ASSERT_STREQ(si::Amount::UNITS, "mol");
        ASSERT_STREQ(si::Angle::UNITS, "rad");
        ASSERT_STREQ(si::SolidAngle::UNITS, "sr");
        ASSERT_STREQ(si::Area::UNITS, "m^2");
        ASSERT_STREQ(si::Volume::UNITS, "m^3");
        ASSERT_STREQ(si::Velocity::UNITS, "m/s");
        ASSERT_STREQ(si::Acceleration::UNITS, "m/s^2");
        ASSERT_STREQ(si::Jerk::UNITS, "m/s^3");
        ASSERT_STREQ(si::Snap::UNITS, "m/s^4");
        ASSERT_STREQ(si::Crackle::UNITS, "m/s^5");
        ASSERT_STREQ(si::Pop::UNITS, "m/s^6");
        ASSERT_STREQ(si::Wavenumber::UNITS, "m^-1");
        ASSERT_STREQ(si::Density::UNITS, "kg/m^3");
        ASSERT_STREQ(si::SurfaceDensity::UNITS, "kg/m^2");
        ASSERT_STREQ(si::SpecificVolume::UNITS, "m^3/kg");
        ASSERT_STREQ(si::CurrentDensity::UNITS, "A/m^2");
        ASSERT_STREQ(si::MagneticFieldStrength::UNITS, "A/m");
        ASSERT_STREQ(si::Concentration::UNITS, "mol/m^3");
        ASSERT_STREQ(si::Luminance::UNITS, "cd/m^2");
        ASSERT_STREQ(si::Illuminance::UNITS, "cd/m^2");
        ASSERT_STREQ(si::Frequency::UNITS, "Hz");
        ASSERT_STREQ(si::Force::UNITS, "N");
        ASSERT_STREQ(si::Pressure::UNITS, "Pa");
        ASSERT_STREQ(si::Stress::UNITS, "Pa");
        ASSERT_STREQ(si::EnergyDensity::UNITS, "Pa");
        ASSERT_STREQ(si::Energy::UNITS, "J");
        ASSERT_STREQ(si::Work::UNITS, "J");
        ASSERT_STREQ(si::Heat::UNITS, "J");
        ASSERT_STREQ(si::Power::UNITS, "W");
        ASSERT_STREQ(si::RadiantFlux::UNITS, "W");
        ASSERT_STREQ(si::Charge::UNITS, "C");
        ASSERT_STREQ(si::Potential::UNITS, "V");
        ASSERT_STREQ(si::Capacitance::UNITS, "F");
        ASSERT_STREQ(si::Resistance::UNITS, "Ohm");
        ASSERT_STREQ(si::Conductance::UNITS, "S");
        ASSERT_STREQ(si::MagneticFlux::UNITS, "Wb");
        ASSERT_STREQ(si::MagneticFluxDensity::UNITS, "T");
        ASSERT_STREQ(si::Inductance::UNITS, "H");
        ASSERT_STREQ(si::LuminousFlux::UNITS, "cd*sr");
        ASSERT_STREQ(si::Activity::UNITS, "Hz");
        ASSERT_STREQ(si::AbsorbedDose::UNITS, "Gy");
        ASSERT_STREQ(si::Kerma::UNITS, "Gy");
        ASSERT_STREQ(si::SpecificEnergy::UNITS, "Gy");
        ASSERT_STREQ(si::DoseEquivalent::UNITS, "Gy");
        ASSERT_STREQ(si::CatalyticActivity::UNITS, "kat");
        ASSERT_STREQ(si::DynamicViscosity::UNITS, "Pa*s");
        ASSERT_STREQ(si::KinematicViscosity::UNITS, "m^2/s");
        ASSERT_STREQ(si::Moment::UNITS, "J");
        ASSERT_STREQ(si::SurfaceTension::UNITS, "N/m");
        ASSERT_STREQ(si::AngularVelocity::UNITS, "rad/s");
        ASSERT_STREQ(si::AngularAcceleration::UNITS, "rad/s^2");
        ASSERT_STREQ(si::AngularJerk::UNITS, "rad/s^3");
        ASSERT_STREQ(si::AngularSnap::UNITS, "rad/s^4");
        ASSERT_STREQ(si::AngularCrackle::UNITS, "rad/s^5");
        ASSERT_STREQ(si::AngularPop::UNITS, "rad/s^6");
        ASSERT_STREQ(si::HeatFluxDensity::UNITS, "W/m^2");
        ASSERT_STREQ(si::Irradiance::UNITS, "W/m^2");
        ASSERT_STREQ(si::HeatCapacity::UNITS, "J/K");
        ASSERT_STREQ(si::Entropy::UNITS, "J/K");
        ASSERT_STREQ(si::SpecificHeatCapacity::UNITS, "J/(kg*K)");
        ASSERT_STREQ(si::SpecificEntropy::UNITS, "J/(kg*K)");
        ASSERT_STREQ(si::ThermalConductivity::UNITS, "W/(m*K)");
        ASSERT_STREQ(si::ElectricFieldStrength::UNITS, "V/m");
        ASSERT_STREQ(si::ElectricChargeDensity::UNITS, "C/m^3");
        ASSERT_STREQ(si::SurfaceChargeDensity::UNITS, "C/m^2");
        ASSERT_STREQ(si::ElectricFluxDensity::UNITS, "C/m^2");
        ASSERT_STREQ(si::ElectricDisplacement::UNITS, "C/m^2");
        ASSERT_STREQ(si::Permittivity::UNITS, "F/m");
        ASSERT_STREQ(si::Permeability::UNITS, "H/m");
        ASSERT_STREQ(si::MolarEnergy::UNITS, "J/mol");
        ASSERT_STREQ(si::MolarEntropy::UNITS, "J/(mol*K)");
        ASSERT_STREQ(si::MolarHeatCapacity::UNITS, "J/(mol*K)");
        ASSERT_STREQ(si::Exposure::UNITS, "C/kg");
        ASSERT_STREQ(si::AbsorbedDoseRate::UNITS, "Gy/s");
        ASSERT_STREQ(si::RadiantIntensity::UNITS, "W/sr");
        ASSERT_STREQ(si::Radiance::UNITS, "W/(m^2*sr)");
        ASSERT_STREQ(si::CatalyticActivityConcentration::UNITS, "kat/m^3");
        ASSERT_STREQ(si::Action::UNITS, "J*s");
    }



    //  == METHOD TESTS ==
    //  -- Getters --



} // namespace test



//  == CLEAN UP ==
//  -- Warnings --
#ifdef __clang__
#pragma clang diagnostic pop
#endif
